### PR TITLE
Update breadcrumbs in children screen

### PR DESCRIPTION
**Pull request by cristinaverdi**

### CODE REVIEW

**Review by ashikka — CHANGES_REQUESTED** [review]
@cristinaverdi could we do the same for the LogEntry page?

**Comment by cristinaverdi** [comment]
> @cristinaverdi could we do the same for the LogEntry page?

Do you mean this?

```js
          links={[
            { name: 'Dashboard', href: PATH_APP.root },
            { name: 'Child', href: PATH_APP.management.user.children },
            { name: 'Log entries' }
          ]}
```

**Comment by ashikka** [comment]
> > @cristinaverdi could we do the same for the LogEntry page?
> 
> Do you mean this?
> 
> ```js
>           links={[
>             { name: 'Dashboard', href: PATH_APP.root },
>             { name: 'Child', href: PATH_APP.management.user.children },
>             { name: 'Log entries' }
>           ]}
> ```

Yup!

**Comment by cristinaverdi** [comment]
> > > @cristinaverdi could we do the same for the LogEntry page?
> > 
> > 
> > Do you mean this?
> > ```js
> >           links={[
> >             { name: 'Dashboard', href: PATH_APP.root },
> >             { name: 'Child', href: PATH_APP.management.user.children },
> >             { name: 'Log entries' }
> >           ]}
> > ```
> 
> Yup!

OK That was already done in a previous PR :)

**Comment by ashikka** [comment]
> > > > @cristinaverdi could we do the same for the LogEntry page?
> > > 
> > > 
> > > Do you mean this?
> > > ```js
> > >           links={[
> > >             { name: 'Dashboard', href: PATH_APP.root },
> > >             { name: 'Child', href: PATH_APP.management.user.children },
> > >             { name: 'Log entries' }
> > >           ]}
> > > ```
> > 
> > 
> > Yup!
> 
> OK That was already done in a previous PR :)

Oh awesome!

**Review by ashikka — APPROVED** [review]

**Pull request merged**
